---  
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cypress/included
    tag: 9.2.0
inputs:
  - name: source-code
outputs:
  - name: source-code
run:
  path: sh
  args:
    - -exec
    - |
      cd source-code
      npm run cy:ci
# fly -t tictactoe execute -c e2e-test-task.yml
